### ISSUE TITLE
xournal ne souvre pas

### ISSUE THREAD

**Issue by Ilistro** [aurelienpierre/TeXmaker-note#1]
J'ai suivi la doc, mais Texmaker me renvoient une erreur quand j'essaye de lancer la commande utilisateur.

`Traceback (most recent call last): File "/home/abel/Documents/TeXmaker-note-1.0/texmaker-note.py", line 178, in <module> OpenXournal(i) File "/home/abel/Documents/TeXmaker-note-1.0/texmaker-note.py", line 114, in OpenXournal process = subprocess.Popen(['xournal', path], stdout=subprocess.PIPE, stderr=subprocess.STDOUT) File "/usr/lib/python3.7/subprocess.py", line 775, in __init__ restore_signals, start_new_session) File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child raise child_exception_type(errno_num, err_msg, err_filename) FileNotFoundError: [Errno 2] No such file or directory: 'xournal': 'xournal'`

Toutefois texmaker-note a crée un répertoire img avec .xjoi et le .log ne semble pas allarment :

` = Base directory created =
= Index initialized =
---
Index : 1
Template Xournal file : 
	created
	compressed
	ready to use
`

Une idée, de ce qui se passe ?
Merci d'avance.

**Comment by danaelg** [comment]
vu le message d'erreur, on dirait qu'il ne trouve pas la commande xournal.
Est-il bien installé ?
Tu peux essayer de lancer la commande `xournal` dans un terminal pour vérifier qu'il se lance bien
